### ISSUE TITLE
Chargement conditionnel des dépendances et minification indépendante de code métier

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/beapi-frontend-framework#11]
Dans la même optique d'optimisation du chargement d'un site que la mise en place du "Deffer", serait-il possible de gérer le chargement conditionnel de dépendances et la minification indépendante de code métier ?

Je m'explique, sur certaines pages, il est nécessaire d'avoir Masonry, sur d'autres, Isotope, etc. Mais il n'y a aucun intérêt d'avoir le code métier systématiquement chargé dans le scripts.min.

Prenons un exemple, j'ai uniquement besoin de Masonry sur ma Homepage :
- Est-ce que charger 2 fichiers minifiés (moins lourd), uniquement sur la homepage, n'est pas moins rapide qu'un seul (script) plus lourd ?
- Mais également avoir un seul fichier minifé (script) plus léger sur toutes les autres pages, ne nécessitant pas de code métier JavaScript Masonry, ne serait pas plus rapide ?

De même, conditionner le chargement des dépendances, par exemple Mansonry uniquement sur la homepage, ce qui réduit le nombre de fichiers chargés n'améliorerait pas les temps de chargement ?

**Comment by Cocola** [comment]
@MaximeCulea En effet cet une bonne piste d'optimisation.

Il faudrait créer une build par gabarits de page.
du style:

```
<html>
<head></head>
<body>
  <script src="modernizr"></script>
  <script src="jquery"></script>
  <script defer src="build.homepage.min.js"></script>
</body>
</html>
```
Cela demande à revoir notre architecture mais ce n'est pas impossible. A voir si on la glisse dans notre migration vers webpack.
Un avis les autres ?

**Comment by MaximeCulea** [comment]
Ca semble bien, après dans un court terme, il est possible d'enqueue conditionnellement en PHP les scripts :
```
if ( is_home() ) {
   wp_enqueue_script( 'mansonry' );
} elseif ( is_search() ) {
   wp_enqueue_script( 'isotop' );
}
```

**Comment by Cocola** [comment]
Après réflexion en R&D, ce traitement reste du cas par cas et nous le faisons déjà au quotidien.
Par exemple, une map custom qui utilise la Google Map API aura sont propre bundle. Idem pour les modules React.
On ne peut donc pas automatiser ce process mais rester conscient de ce que peut peser notre build et donc d'appliquer ces bonnes pratiques au quotidien.
