### ISSUE TITLE
Utilisation d'une solution de guide de styles pour l'intégration statique

### ISSUE THREAD

**Issue by francoistibo** [BeAPI/beapi-frontend-framework#121]
Une solution du type Fractal : https://fractal.build/

Avantages : 

- orienté composants
- qualité ++
- pratique ++ (on peut faire des variantes de composants)
- construction d'un guide de styles qui pourra être utilisé par n'importe quel dév arrivant sur le projet (bibliothèque de composants)
- outil final peut être vendu au client au besoin
- intégration dans les VRAIS fichiers du thème wordpress (pas de dossier SRC) qui évite la copie/doublonnage en passage back

**Comment by firestar300** [comment]
Je pense qu'une présentation de l'outil s'impose lorsqu'on fera une réunion ensemble afin que tout le monde en prenne connaissance.

**Comment by francoistibo** [comment]
solution : story book testée par @firestar300
