### ISSUE TITLE
Ajouter de base le style page login

### ISSUE THREAD

**Issue by francoistibo** [BeAPI/beapi-frontend-framework#122]
[A discuter]

- feuille de style dédiée dans BFF, dans le dossier src/scss (stylesheet minifiée toute seule via webpack (l'inclure dans les settings webpack) dans dist pour l'appeler via le hook add_action('login_head') dans le service assets
- logo (SVG dans l'idéal) dédié à la page login stocké dans src/img/static

**Comment by Rahe** [comment]
Hello,

Pour moi c'est clairement dans le scope d'un mu-plugin.
Cependant ce mu-plugin peut s'appuyer sur le thème pour :

- Proposer une manière d'ajouter du CSS inline/fichier sur la bonne page
- Utiliser le logo mis à disposition par le thème dans un dossier
- Modifier du comportement

**Comment by francoistibo** [comment]
Ouais carrément, un plugin qui pioche dans le thème peut être carrément pratique.

**Comment by firestar300** [comment]
Il peut être intéressant de créer un plugin maison alors pour cette fonctionnalité.

**Comment by firestar300** [comment]
@Rahe ,

Je ne suis pas d'accord, la charte graphique de la page login est liée à la charte graphique du thème, du coup je ne trouve pas ça aberrant que ce soit intégré au BFF.

**Comment by francoistibo** [comment]
bon du coup, en réunion front et avec le recul, on est tous à peu près d'accord pour que ca reste dans le thème dans le sens ou ce sont les styles de cette page peuvent etre deja dans le theme, reprendre les couleurs de la charte direct (include des variables colors) et le logo choisi pour cette page deja stocké dans les assets (img/static/logo-login.svg par exemple). avec ce système, ca prend 2 min de personnaliser le login page, qui au final ne bouge pas une fois qu'elle est faite.

**Comment by Rahe** [comment]
@firestar300 Oui, mais parfois le thème est un thème blank, du coup sur la page d'accueil de la plateforme aucune personnalisation possible.

3 cas pour moi que le mu gère :
1. Le thème défini quelque chose : ça pioche CSS/Image dans des paths définis
2. Le thème ne défini rien : on pioche dans un dossier en particulier pour voir s'il y a quelque chose
3. Le thème ne défini rien et ya rien dans le dossier ci-dessus : on pioche dans les assets par défaut du mu

**Comment by Rahe** [comment]
Il faut utiliser https://github.com/BeAPI/wp-login-page/ pour ça :)
