### ISSUE TITLE
Problème de condition dans Assets.php

### ISSUE THREAD

**Issue by firestar300** [BeAPI/beapi-frontend-framework#161]
@Rahe ,

Je suis en train de migrer le BFF sur Webpack 5, j'ai mis en place sur ma machine une instance Lando à partir du skeleton comme si j'initialisais une nouveau projet comme c'est indiqué sur Notion.

J'ai rencontré un soucis sur l'import du script app.js dans `Services/Assets.php`
```php
// Async and footer
$file = ( ! defined( 'SCRIPT_DEBUG' ) || SCRIPT_DEBUG === false ) ? $this->get_min_file( 'js' ) : 'app.js';
$this->assets_tools->register_script( 'scripts', 'dist/' . $file, $scripts_dependencies, $theme->get( 'Version' ), true );
```

`$file` retourne un boolean alors qu'il devrait retourner une string.

**Comment by Rahe** [comment]
Je pense que si tu as un false ou true c'est que ton "SCRIPT_DEBUG" est pas à true, car il va chercher la version minifiée dans ce cas et que tu devais pas en avoir une en place.
Possiblement changer la signature de la fonction pour retourner un string vide en cas d'erreur

**Comment by firestar300** [comment]
Très bizarre, j'avais fait un `var_dump( ( ! defined( 'SCRIPT_DEBUG' ) || SCRIPT_DEBUG === false ) )` et ça me retournait `true` mais ça doit être ça alors.
