### ISSUE TITLE
Helpers - Svg 

### ISSUE THREAD

**Issue by n-langle** [BeAPI/beapi-frontend-framework#166]
Les fonctions the_icon et get_the_icon ne devraient elles pas retourner une chaîne vide si l'icône est indéfinie (dans le cas d'une utilisation avec un champ acf par exemple) :

`
the_icon( get_field( 'icon' ) ); // -> return '<svg class="icon icon-" ...</svg>'
`

**Comment by Rahe** [comment]
Clairement, à modifier :)

**Comment by Rahe** [comment]
Dans la PR #171 171
