### ISSUE TITLE
Clean BFF (Tech days #1)

### ISSUE THREAD

**Issue by francoistibo** [BeAPI/beapi-frontend-framework#168]
Traiter https://github.com/BeAPI/beapi-frontend-framework/issues/165 au préalable

**A supprimer :** 

- Service Sidebar
- Functions.php : suppression des require (qui ne sont utilisés que pour les helpers, qui pourraient donc passer en plugin/dépendances (cf. au-dessus)). cf https://github.com/BeAPI/beapi-frontend-framework/issues/165

**Comment by firestar300** [comment]
@francoistibo On peut fermer ?
