### ISSUE TITLE
BFF Front + back

### ISSUE THREAD

**Issue by Rahe** [BeAPI/beapi-frontend-framework#20]
J'ai commencé à bosser sur une base thème BFF Front+Back avec autoload et modernisation.
Je suis passé sur les projets récents pour récupérer et isoler les composants récurrents et leur intégration.
Je suis sur une branchz du bff et c'st un gros *BROUILLON* donc faudra potentiellement refactor, commenter et remplir le readme/wiki pour l'utilisation de celui-ci.

Si jamais vous voyez des composants manquants, listez les que l'on puisse les ajouter.

https://github.com/BeAPI/beapi-frontend-framework/tree/feature/starter-php

**Comment by Cocola** [comment]
@Rahe j'ai jeter un coup d'oeil en local, c'est vraiment une bonne base selon moi. Je vois juste un inconvénient, la dépendance à ACF. En interne ce n'est pas un problème, pour le monde extérieur je trouve ça fermer si l'on veut un peu plus ouvrir notre stack au monde.
Sinon je pense qu'il nous faudrait également:

- [ ] header (sur la base du modèle statique)
- [ ] menu (sur la base du modèle statique)
- [ ] footer (sur la base du modèle statique)
- [ ] vue archive (sur la base du modèle statique)
- [ ] vue résultat de recherche (sur la base de la vue archive)
- [ ] single (sur la base du modèle statique)
- [ ] page (sur la base du modèle single)

**Comment by firestar300** [comment]
Quid de cette issue ? @Cocola @Rahe

**Comment by Rahe** [comment]
On a mergé mes commits il y a un moment je pense, a re-refactor je pense :)
