### ISSUE TITLE
Helper pour the_time()

### ISSUE THREAD

**Issue by firestar300** [BeAPI/beapi-frontend-framework#222]
On utilise souvant ce genre de markup:
```php
<time class="date__time" datetime="<?php echo get_the_date( 'Y-m-d' ); ?>"><?php echo get_the_date(); ?></time>
```

Possible d'en faire un helper ?

**Comment by francoistibo** [comment]
@Rahe ?

**Comment by Rahe** [comment]
Hello,

Oui, je pense qu'il aurait plus sa place en mode template, on donne dans les args les données à afficher et voilà.
A discuter mais oui :)

Nicolas,

**Comment by firestar300** [comment]
[`the_time();`](https://developer.wordpress.org/reference/functions/the_time/) existe déjà. Je ferme l'issue.
