### ISSUE TITLE
Rajouter un écouteur passif par défaut

### ISSUE THREAD

**Issue by firestar300** [BeAPI/beapi-frontend-framework#225]
Voir https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=lr#how-to-make-event-listeners-passive-to-improve-scrolling-performance

**Comment by Rahe** [comment]
Implémentable dans jQuery avec https://stackoverflow.com/a/62177358

**Comment by firestar300** [comment]
Résolu dans #226
