### ISSUE TITLE
Internationnalisation

### ISSUE THREAD

**Issue by Rahe** [BeAPI/beapi-frontend-framework#228]
Il manque 
1. Charger le fichier de trad du thème
2. Dans le style.css le language-path et text-domain

**Comment by firestar300** [comment]
Par défaut, le domaine path pointe vers `/languages`. Donc pas besoin de l'ajouter dans `style.css`. Pour le reste, c'est fait.

> **Domain Path:** Used so that WordPress knows where to find the translation when the theme is disabled. Defaults to /languages.

https://developer.wordpress.org/themes/basics/main-stylesheet-style-css/#explanations
