### ISSUE TITLE
All ? 

### ISSUE THREAD

**Issue by Cocola** [BeAPI/beapi-frontend-framework#23]
https://github.com/BeAPI/beapi-frontend-framework/blob/4ec2969cf9ce33ad85a90b86d9346429d1de1088/assets/js/src/menu.js#L37

@Nkzq ⬆️

**Comment by Nkzq** [comment]
https://github.com/BeAPI/beapi-frontend-framework/blob/d6432cf4c4722e0982871029a35b7e09b38ef4d9/assets/js/src/menu.js#L37
