### ISSUE TITLE
Utilité des classes js/no-js

### ISSUE THREAD

**Issue by Rahe** [BeAPI/beapi-frontend-framework#272]
Hello,

On a ce JS dans le thème : 
https://github.com/BeAPI/beapi-frontend-framework/blob/master/header.php#L4

Est-il utile ?

Niolas,

**Comment by n-langle** [comment]
@Rahe Oui, c'est à conserver. Elles permettent de gérer les fallbacks sans avoir de reflow/repaint au chargement de la page

**Comment by Rahe** [comment]
Ok super, merci :)
