### ISSUE TITLE
Ne pas afficher le bouton et le menu principal si aucun menu n'est défini

### ISSUE THREAD

**Issue by MarieComet** [BeAPI/beapi-frontend-framework#324]
Actuellement, le bouton d'ouverture du menu principal ainsi que la balise nav sont affichés même si aucun menu n'est défini sur le thème location "menu-main".
Il serait préférable de ne pas les afficher dans ce cas, en ajoutant une condition sur `has_nav_menu` dans /components/parts/common/header.php

**Comment by francoistibo** [comment]
+1. Tu peux faire la PR @MarieComet (recopie correctif FrenchDays par exemple) quand tu as le temps.
