### ISSUE TITLE
Due to assets renaming folder, change path to bea image

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/beapi-frontend-framework#34]
In order to make bea image to work, we must change path : https://github.com/BeAPI/beapi-frontend-framework/blob/master/dist/functions/_init.php.
Due to https://github.com/BeAPI/beapi-frontend-framework/commit/41df1f537e166ab2e8c79b49019b11a4ae7fea9c

**Comment by Cocola** [comment]
done : https://github.com/BeAPI/beapi-frontend-framework/commits/master
