### ISSUE TITLE
BFF breakpoints VS Gutenberg breakpoints

### ISSUE THREAD

**Issue by MarieComet** [BeAPI/beapi-frontend-framework#359]
Les breakpoints BFF sont les suivants :
````
xs: 600,
sm: 768,
admin-bar: 784,
smd: 900,
md: 1200,
lg: 1440,
xlg: $container-wide + 160px
````

Les [breakpoints Gutenberg](https://github.com/WordPress/gutenberg/blob/5ba748472b3e481e89ec3ac4c4e215031cc1eb3c/packages/base-styles/_breakpoints.scss#L6-L13) sont les suivants : 
````
$break-huge: 1440px;
$break-wide: 1280px;
$break-xlarge: 1080px;
$break-large: 960px;	// admin sidebar auto folds
$break-medium: 782px;	// adminbar goes big
$break-small: 600px;
$break-mobile: 480px;
$break-zoomed-in: 280px;

````

Cela pose problème pour matcher le CSS responsive, par exemple pour le bloc colonnes.
Quid d'une uniformisation de BFF par rapport à Gut ?

**Comment by Rahe** [comment]
C'est personnalisable dans gut ?

**Comment by Rahe** [comment]
C'est personnalisable dans gut ?

**Comment by firestar300** [comment]
Je serais d'avis à uniformiser mais parfois on a des contraintes maquettes externes qui nous imposent des breakpoints spécifiques (Infopro Digital, Kiloutou...)

**Comment by Rahe** [comment]
Est-ce qu'il ya une liaison avec le "contentSize" et "wideSize" du theme.json ? (vu qu'ils sont personnalisables)

**Comment by MarieComet** [comment]
Non

**Comment by francoistibo** [comment]
TODO @MarieComet : créer PR

**Comment by francoistibo** [comment]
Estimation : 30min (tests inclus)
