### ISSUE TITLE
We should discuss about schema.org implementation

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/beapi-frontend-framework#39]
Bilal tells me that we don't need anymore this following properties :
- itemprop
- itemscope
- itemtype

**Comment by Cocola** [comment]
We already discuss about that. Normally there is no more schema.org occurencies in our source files.
It's now synced with the WordPress header.php : https://github.com/BeAPI/beapi-frontend-framework/commit/c448631fd21879a2e42bbd52da84842105ce1d22

**Comment by MaximeCulea** [comment]
You are right, nothing else into the BFF.
