### ISSUE TITLE
BFF Windows 10 & serveur local

### ISSUE THREAD

**Issue by predawi** [BeAPI/beapi-frontend-framework#43]
Il y a des petits ajustements à apporter pour faire tourner le serveur local sous windows 10.

Dans le package.json, dans le script "start", il faut ajouter un & entre dev et webpack : 
`NODE_ENV=dev & webpack`

Et dans server.js, cette ligne pose problème : 
`proxy: 'http://[::1]:' + config.port,`

Le serveur local se bloque en infinite loop. Du coup il suffit de changer pour : 
`proxy: 'http://localhost:' + config.port,`

Je n'ai pas testé sur mac si ça fonctionnait.

**Comment by Cocola** [comment]
Yo @predawi ! Tu peux faire une PR ? on testera sur mac et si c'est bon on merge !

**Comment by firestar300** [comment]
Hello ! De mémoire `'http://localhost:' + config.port,` posait justement problème sur OSX mais avec la future version de BFF avec Pug, le problème sera fix car le proxy se fait sur localhost et c'est fonctionnel sur Mac.

**Comment by Nkzq** [comment]
Hello @predawi,

Je te laisse faire un petit `git pull` pour récupérer le commit suivant : https://github.com/BeAPI/beapi-frontend-framework/commit/76f1a664ab090b5e31eb7cfc523ad4a57f310d94

Et fermer l'issue si le soucis est réparé 😄
