### ISSUE TITLE
Editor style

### ISSUE THREAD

**Issue by Cocola** [BeAPI/beapi-frontend-framework#46]
Webpack génère un fichier css dédié au wysiwyg dans `dist/assets/editor-style.css`
J'essaie de l'ajouter mais sans succes, mon commit : https://github.com/BeAPI/beapi-frontend-framework/commit/2a67b1fefa4a2f247a5d187b8a20291f7e3536e4

**Comment by Rahe** [comment]
Corrigé dans https://github.com/BeAPI/beapi-frontend-framework/commit/be0fc220d5cd19ffdeebeac576e443ea13f267f4
