### ISSUE TITLE
Add .github/CODEOWNERS file

### ISSUE THREAD

**Issue by Rahe** [BeAPI/beapi-frontend-framework#58]
Hello,

We can add automatic assigned people to issues based on the folders/file types like Gutenberg project have one  
* Gutenberg : https://github.com/WordPress/gutenberg/blob/master/.github/CODEOWNERS
* Documentation : https://help.github.com/en/articles/about-code-owners

We can in this case associate .php files to the backend dev and .scss, .js etc. to the frontend dev.

Ideas on this ?
File types to be automatically associated with ?

**Comment by firestar300** [comment]
En gros c'est pour les PR ?

**Comment by Rahe** [comment]
Yeap :)
En gros en fonction des ttpes de fichiers on peut associer directement les personnes à la PR :)
