### ISSUE TITLE
Compatibilty scripts loader FacetWP

### ISSUE THREAD

**Issue by asadowski10** [BeAPI/beapi-frontend-framework#59]
Hi team,

The FacetWP plugin loads at wp_footer () but our main script (scripts.min.js // app.min.js) loads before.
As a result, we do not have access to the FW object and therefore cause an error in the loading of the pages.

Should not we, load our scripts to wp_footer ()?

Thanks

**Comment by Rahe** [comment]
Hello,

The script is on async/defer by default, so we shouldn't have to put it on the footer.
We need to use the FacetWP events https://facetwp.com/documentation/developers/javascript/facetwp-loaded/ to handle the facet ready and not using the FacetWP APi directly.
