### ISSUE TITLE
Le preload CSS ne fonctionne pas sur Firefox

### ISSUE THREAD

**Issue by firestar300** [BeAPI/beapi-frontend-framework#62]
Actuellement le preload CSS ne fonctionne pas sur Firefox ce qui nous oblige à le désactiver sur les projets. L'action se trouve dans `assets-css-async.php` au même endroit que le chargement du script JS de chargements des fonts.

Soit on désactive le preload CSS en retirant l'action : `add_action( 'wp_head', [ $this, 'load_css' ], 0 );`

Soit on trouve une alternative pour le preload CSS : https://www.filamentgroup.com/lab/load-css-simpler/

**Comment by Rahe** [comment]
PR sur https://github.com/BeAPI/beapi-frontend-framework/pull/63
