### ISSUE TITLE
Remove favicons node task from BFF

### ISSUE THREAD

**Issue by firestar300** [BeAPI/beapi-frontend-framework#73]
In order to reduce the node_modules/ size, @Cocola suggested to remove favicons task from BFF.

- [x] Remove `favicons` dependency
- [x] Remove `scripts/favicon.js` script
- [x] Remove `npm run favicon` from package.json
- [x] Remove unused `<link>` in `src/templates/partials/header.php`
- [x] Remove unused `<link>` in header WordPress side

**Comment by Cocola** [comment]
https://github.com/BeAPI/beapi-frontend-framework/pull/74
